# Generated by Django 3.0.6 on 2020-05-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_group'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='subject',
            field=models.ManyToManyField(to='subjects.Subject'),
        ),
    ]
