# Generated by Django 3.0.6 on 2020-05-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level_3',
            field=models.FloatField(default=25),
        ),
        migrations.AddField(
            model_name='subject',
            name='level_4',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='subject',
            name='level_5',
            field=models.FloatField(default=75),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('deadline', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.Subject')),
            ],
        ),
    ]
